//! Generate typed-node accessors from tree-sitter-greycat's `node-types.json`.
//!
//! For each named node kind we emit a newtype wrapper around `tree_sitter::Node`
//! with field accessors (`child_by_field_name`). Subtype dispatch is left to the
//! caller via the `NodeExt::cast` extension method.

use std::collections::BTreeMap;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

use serde::Deserialize;

#[derive(Deserialize)]
struct NodeType {
    #[serde(rename = "type")]
    kind: String,
    named: bool,
    #[serde(default)]
    fields: BTreeMap<String, Children>,
    #[serde(default)]
    children: Option<Children>,
    #[serde(default)]
    subtypes: Vec<TypeRef>,
}

#[derive(Deserialize)]
#[allow(dead_code)]
struct Children {
    #[serde(default)]
    multiple: bool,
    #[serde(default)]
    required: bool,
    #[serde(default)]
    types: Vec<TypeRef>,
}

#[derive(Deserialize)]
#[allow(dead_code)]
struct TypeRef {
    #[serde(rename = "type")]
    kind: String,
    #[serde(default)]
    named: bool,
}

fn pascal_case(s: &str) -> String {
    let mut out = String::new();
    let mut up = true;
    for c in s.chars() {
        if c == '_' {
            up = true;
        } else if up {
            out.extend(c.to_uppercase());
            up = false;
        } else {
            out.push(c);
        }
    }
    out
}

fn screaming_snake(s: &str) -> String {
    s.to_ascii_uppercase()
}

/// Wrap Rust keywords with the raw-identifier prefix so we can use any field
/// name from the grammar verbatim as a method name.
fn rust_ident(s: &str) -> String {
    matches!(
        s,
        "as" | "break"
            | "const"
            | "continue"
            | "crate"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "async"
            | "await"
            | "dyn"
            | "abstract"
            | "become"
            | "box"
            | "do"
            | "final"
            | "macro"
            | "override"
            | "priv"
            | "typeof"
            | "unsized"
            | "virtual"
            | "yield"
            | "try"
            | "union"
    )
    .then(|| format!("r#{s}"))
    .unwrap_or_else(|| s.to_string())
}

fn main() {
    // Single source of truth: read node-types.json directly from the
    // tree-sitter-greycat submodule. No vendored copy in this crate.
    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap());
    let json_path = manifest_dir
        .parent()
        .expect("syntax crate has a parent dir")
        .join("vendor/tree-sitter-greycat/src/node-types.json");

    println!("cargo:rerun-if-changed={}", json_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let json = fs::read_to_string(&json_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", json_path.display()));
    let nodes: Vec<NodeType> = serde_json::from_str(&json).expect("parse node-types.json");

    let mut out = String::new();
    out.push_str("// Generated by build.rs from node-types.json. Do not edit.\n\n");

    // Kind constants
    out.push_str("/// Tree-sitter node kind strings, one constant per named node.\n");
    out.push_str("pub mod kind {\n");
    for n in &nodes {
        if !n.named {
            continue;
        }
        let _ = writeln!(
            out,
            "    pub const {}: &str = \"{}\";",
            screaming_snake(&n.kind),
            n.kind
        );
    }
    out.push_str("}\n\n");

    // TypedNode trait + cast extension
    out.push_str(
        "pub trait TypedNode<'tree>: Sized + Copy {\n\
         \x20   const KIND: &'static str;\n\
         \x20   fn cast(node: tree_sitter::Node<'tree>) -> Option<Self>;\n\
         \x20   fn node(&self) -> tree_sitter::Node<'tree>;\n\
         }\n\n\
         pub trait NodeExt<'tree> {\n\
         \x20   fn cast<T: TypedNode<'tree>>(self) -> Option<T>;\n\
         }\n\n\
         impl<'tree> NodeExt<'tree> for tree_sitter::Node<'tree> {\n\
         \x20   fn cast<T: TypedNode<'tree>>(self) -> Option<T> {\n\
         \x20       T::cast(self)\n\
         \x20   }\n\
         }\n\n",
    );

    // Per-kind newtype wrappers
    for n in &nodes {
        if !n.named {
            continue;
        }
        // Skip nodes whose kind isn't a valid Rust identifier base.
        // (All current named kinds in greycat are snake_case identifiers; this
        // is defensive in case the grammar ever introduces something exotic.)
        if !n
            .kind
            .chars()
            .next()
            .map(|c| c.is_ascii_alphabetic() || c == '_')
            .unwrap_or(false)
        {
            continue;
        }

        let struct_name = pascal_case(&n.kind);
        let kind_str = &n.kind;

        let _ = writeln!(out, "/// `{kind_str}` node.");
        let _ = writeln!(out, "#[derive(Clone, Copy, Debug)]");
        let _ = writeln!(
            out,
            "pub struct {struct_name}<'tree>(tree_sitter::Node<'tree>);"
        );
        out.push('\n');
        let _ = writeln!(
            out,
            "impl<'tree> TypedNode<'tree> for {struct_name}<'tree> {{"
        );
        let _ = writeln!(out, "    const KIND: &'static str = \"{kind_str}\";");
        let _ = writeln!(
            out,
            "    fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {{"
        );
        let _ = writeln!(
            out,
            "        (node.kind() == \"{kind_str}\").then_some({struct_name}(node))"
        );
        let _ = writeln!(out, "    }}");
        let _ = writeln!(
            out,
            "    fn node(&self) -> tree_sitter::Node<'tree> {{ self.0 }}"
        );
        out.push_str("}\n\n");

        if !n.fields.is_empty() || n.children.is_some() {
            let _ = writeln!(out, "impl<'tree> {struct_name}<'tree> {{");
            for field_name in n.fields.keys() {
                let method = rust_ident(field_name);
                let _ = writeln!(out, "    /// `{field_name}` field accessor.");
                let _ = writeln!(
                    out,
                    "    pub fn {method}(&self) -> Option<tree_sitter::Node<'tree>> {{"
                );
                let _ = writeln!(out, "        self.0.child_by_field_name(\"{field_name}\")");
                out.push_str("    }\n");
            }
            // For positional children (no field name), expose a `children()`
            // iterator over named children. Useful for collection-style nodes
            // like `args`, `block`, `module`.
            if n.children.is_some() {
                out.push_str(
                    "    /// Iterator over named children of this node (positional, no field name).\n",
                );
                out.push_str(
                    "    pub fn children(&self) -> impl Iterator<Item = tree_sitter::Node<'tree>> + '_ {\n",
                );
                out.push_str("        let mut cursor = self.0.walk();\n");
                out.push_str(
                    "        let nodes: Vec<_> = self.0.named_children(&mut cursor).collect();\n",
                );
                out.push_str("        nodes.into_iter()\n");
                out.push_str("    }\n");
            }
            out.push_str("}\n\n");
        }

        // Silence unused-warnings for grammar fields we don't yet consume.
        let _ = (&n.subtypes, &n.children);
    }

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").unwrap());
    fs::write(out_dir.join("generated.rs"), out).expect("write generated.rs");
}
