#!/usr/bin/env node
// Sync the TextMate grammar from the single source of truth at
// `editors/code/grammar/Greycat.tmLanguage.json` into this package's
// `src/` so tsdown can bundle it. Runs as part of `pnpm build`.
//
// The grammar lives in the VSCode extension because that's where it
// ships first (P0 of every grammar change). This package mirrors it
// 1:1 — diverging here would mean Shiki and VSCode drift.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..", "..", "..");

const grammarPath = resolve(repoRoot, "editors", "code", "grammar", "Greycat.tmLanguage.json");
const outPath = resolve(__dirname, "..", "src", "grammar.generated.ts");

const grammar = JSON.parse(readFileSync(grammarPath, "utf8"));
const banner = `// AUTO-GENERATED by scripts/sync-grammar.mjs — do not edit.
// Source: editors/code/grammar/Greycat.tmLanguage.json
//
// Regenerate via \`pnpm --filter @greycat/shiki run sync-grammar\`.

`;
const body = `export const greycatGrammar = ${JSON.stringify(grammar, null, 2)} as const;\n`;
writeFileSync(outPath, banner + body);
console.log(`wrote ${outPath}`);
