<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Greycat</string>
    <key>scopeName</key>
    <string>source.gcl</string>
    <key>fileTypes</key>
    <array>
      <string>gcl</string>
    </array>
    <key>uuid</key>
    <string>395c9937-c471-412d-bdd7-43da892e0cee</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#common</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>common</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#doc</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifier-or-keyword</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literals</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#brackets</string>
          </dict>
        </array>
      </dict>
      <key>identifier-or-keyword</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#keyword</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifier</string>
          </dict>
        </array>
      </dict>
      <key>keyword</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>storage.modifier.gcl</string>
            <key>match</key>
            <string>\b(abstract|as|at|break|continue|catch|do|else|enum|extends|for|fn|if|in|is|limit|native|private|sampling|skip|static|throw|try|type|use|var|while|without|task)\b(?![\(\)\]\.\;\:\=\&gt;\}\{\-])</string>
          </dict>
          <dict>
            <key>name</key>
            <string>storage.modifier.gcl</string>
            <key>match</key>
            <string>\b(return|break|continue)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>variable.language.this.gcl</string>
            <key>match</key>
            <string>\b(this)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.language.gcl</string>
            <key>match</key>
            <string>\b(true|false|null)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>variable.other.constant.gcl meta.annotation.gcl</string>
            <key>match</key>
            <string>\@\b[a-zA-Z_][a-zA-Z0-9_]*\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>variable.other.constant.gcl primitive.constant.type.gcl</string>
            <key>match</key>
            <string>\b(int|float|i8|u8|f8|i16|u16|f16|i32|f32|u32|f64|u64|i64|bool|time|duration|geo|any|char|node|nodeTime|nodeIndex|nodeList|nodeGeo)\b(?![\.\(:=}{-])</string>
          </dict>
        </array>
      </dict>
      <key>identifier</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.definition.function.gcl entity.name.function.gcl</string>
            <key>match</key>
            <string>\b([a-zA-Z_][a-zA-Z0-9_]*)\b(?=[^\.(:=;$-&gt;}{]*\()</string>
          </dict>
          <dict>
            <key>name</key>
            <string>variable.other.constant.gcl</string>
            <key>match</key>
            <string>\b((?=_?[A-Z])([a-zA-Z_][a-zA-Z0-9_]*)?)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>variable.other.readwrite.gcl</string>
            <key>match</key>
            <string>\b([a-zA-Z_][a-zA-Z0-9_]*)\b</string>
          </dict>
        </array>
      </dict>
      <key>doc</key>
      <dict>
        <key>begin</key>
        <string>\@doc</string>
        <key>end</key>
        <string>(?=\))</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>variable.other.constant.doc.gcl meta.annotation.doc.gcl</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#doc-markdown</string>
          </dict>
        </array>
      </dict>
      <key>doc-markdown</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(")(.*)(")</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>string.template.begin.doc.gcl</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>comment.block.gcl</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>string.template.end.doc.gcl</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>"</string>
            <key>end</key>
            <string>(?&lt;!\\)\s*(")\s*(?=\))</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>string.template.begin.doc.gcl</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>string.template.end.doc.gcl</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>comment.block.gcl</string>
          </dict>
        </array>
      </dict>
      <key>fenced-code-gcl</key>
      <dict>
        <key>begin</key>
        <string>^(\s*)(`{3,}|~{3,})\s*(?i:(gcl|greycat)((\s+|:|\{)[^`~]*)?$)</string>
        <key>end</key>
        <string>^(\2|\s{0,3})(\3)\s*$</string>
        <key>name</key>
        <string>markup.fenced_code.block.gcl</string>
        <key>beginCaptures</key>
        <dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.gcl</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>fenced_code.block.language.gcl</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>fenced_code.block.language.attributes.gcl</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.gcl</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>^(\s*)</string>
            <key>while</key>
            <string>^(?!\s*([`~]{3,})\s*$)</string>
            <key>contentName</key>
            <string>meta.embedded.block.gcl</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.gcl</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>brackets</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>{</string>
            <key>end</key>
            <string>}|(?=\*/)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#common</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\[</string>
            <key>end</key>
            <string>\]|(?=\*/)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#common</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>literals</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#numeric-literal</string>
          </dict>
        </array>
      </dict>
      <key>numeric-literal</key>
      <dict>
        <key>name</key>
        <string>constant.numeric.gcl</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.numeric.gcl meta.delimiter.underscore.gcl</string>
            <key>match</key>
            <string>_</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([0-9][0-9]*)(\.)?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.decimal.gcl</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.gcl meta.delimiter.decimal.period.gcl</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.numeric.gcl storage.type.numeric.exponent.gcl</string>
            <key>match</key>
            <string>[eE][+-]?</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.numeric.gcl storage.type.numeric.suffix.gcl</string>
            <key>match</key>
            <string>[a-zA-Z_][a-zA-Z0-9_]*</string>
          </dict>
        </array>
      </dict>
      <key>string</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#char-literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#template</string>
          </dict>
        </array>
      </dict>
      <key>char-literal</key>
      <dict>
        <key>name</key>
        <string>string.quoted.single.gcl</string>
        <key>begin</key>
        <string>'</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.gcl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\')|((?:[^\\\n])$)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.gcl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>invalid.illegal.newline.gcl</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string-character-escape</string>
          </dict>
        </array>
      </dict>
      <key>template</key>
      <dict>
        <key>name</key>
        <string>string.template.gcl</string>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.template.begin.gcl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.template.end.gcl</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#template-interpolation</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string-character-escape</string>
          </dict>
        </array>
      </dict>
      <key>template-interpolation</key>
      <dict>
        <key>name</key>
        <string>meta.template.expression.gcl</string>
        <key>begin</key>
        <string>\$\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.template-expression.begin.gcl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.template-expression.end.gcl</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#common</string>
          </dict>
        </array>
        <key>contentName</key>
        <string>meta.embedded.line.gcl</string>
      </dict>
      <key>string-character-escape</key>
      <dict>
        <key>name</key>
        <string>constant.character.escape.gcl</string>
        <key>match</key>
        <string>\\(x[0-9A-Fa-f]{2}|[0-2][0-7]{0,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.|$)</string>
      </dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.block.gcl</string>
            <key>begin</key>
            <string>(/\*)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.gcl</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.gcl</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>(^[ \t]+)?((//)(?:((@)pragma)\s))</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.whitespace.comment.leading.gcl</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>comment.line.double-slash.gcl</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.gcl</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>storage.type.internaldeclaration.gcl</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.decorator.internaldeclaration.gcl</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>variable.other.constant.gcl</string>
                <key>match</key>
                <string>\b((?=_?[A-Z])([a-zA-Z_][a-zA-Z0-9_]*)?)\b</string>
              </dict>
              <dict>
                <key>name</key>
                <string>meta.definition.function.gcl entity.name.function.gcl</string>
                <key>match</key>
                <string>\b([a-zA-Z_][a-zA-Z0-9_]*)\b</string>
              </dict>
            </array>
            <key>contentName</key>
            <string>comment.line.double-slash.gcl</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(^[ \t]+)?((//)(?!@pragma))</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.whitespace.comment.leading.gcl</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>comment.line.double-slash.gcl</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$)</string>
            <key>contentName</key>
            <string>comment.line.double-slash.gcl</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>